name: Elite SDET CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Run Unit Tests
        run: docker compose run --rm tests pytest -m unit -v


  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Full Stack
        run: docker compose up --build --abort-on-container-exit


  performance_tests:
    runs-on: ubuntu-latest
    needs: integration_tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Run Performance Tests
        run: docker compose run --rm tests pytest -m performance -v


  ui_tests:
    runs-on: ubuntu-latest
    needs: performance_tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build

      - name: Run UI Tests
        run: docker compose run --rm tests pytest -m e2e_ui -v